####                         Create Numpy Arrays

In [1]:
import numpy as np

In [2]:
nums = [[1,2,3],[4,5,6]]

In [3]:
nums = np.array(nums)

In [4]:
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
nums.ndim

2

In [6]:
nums.shape

(2, 3)

In [7]:
nums.dtype

dtype('int32')

#### 0.create array using Numpy function

In [8]:
# 1d array printing five zero element 
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [10]:
# 2d array printng zeros
arr = np.zeros((2,3),dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
# 2d array printing ones
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# printing the type of array
arr.ndim

2

In [13]:
# printing 2d diagonal matrix
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
arr = np.eye(3,4,dtype=int)
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [15]:
# 4x4 square metrix : if you giving 4 element
arr = np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [16]:
#if you want to know diagonal of this matrix : use diag()
arr = np.eye(3,4)
np.diag(arr)

array([1., 1., 1.])

In [18]:
# to print random number from 1 to 15 
# between this we need random 4 digit
# 1 in inclusive but it can't print 15 
rand_arr = np.random.randint(1,15,4).reshape(2,2)
rand_arr

array([[14,  2],
       [ 7,  1]])

In [19]:
# It will give 5 floating point number between 0 to 1 
rand_arr = np.random.rand(5)
rand_arr

array([0.31240412, 0.08115718, 0.04852537, 0.59008012, 0.03749238])

In [20]:
# It will give us floating point number between 0 to 1 
# Its a 2d array
# its a uniform distribution 
rand_arr = np.random.rand(2,3)
rand_arr

array([[0.34530112, 0.63859942, 0.42381949],
       [0.18176266, 0.93636885, 0.20409027]])

In [21]:
# it will give us random number centered aroung zero  
# it can be negative
# its a standard normal distribution
rand_arr = np.random.randn(15000)
np.mean(rand_arr)

0.009721068525633099

### 1 : reshaping of data

In [22]:
arr = np.random.randint(1,100,20)
arr = arr.reshape(2,10)

In [23]:
arr

array([[83, 20, 62, 33, 83, 30, 38, 72, 11, 61],
       [89, 45, 86, 80, 89, 69, 81, 13, 68, 78]])

In [24]:
arr.shape

(2, 10)

In [25]:
arr = np.random.randint(1,100,50)
arr = arr.reshape(10,5)
#arr = arr.reshape(50)

In [26]:
arr

array([[99, 72, 36, 91,  1],
       [86,  4, 62, 17, 47],
       [74, 86, 69, 35, 46],
       [89, 40, 60, 34,  1],
       [87, 83, 64, 26, 79],
       [ 2, 44, 32, 64, 83],
       [36,  9, 80, 31, 93],
       [55, 19, 92, 89,  3],
       [16,  9, 11, 47, 15],
       [62, 54,  7, 68, 84]])

In [27]:
arr.ndim

2

In [29]:
arr = np.random.randint(1,100,50)
arr = arr.reshape(2,5,5)
arr

array([[[54, 83, 10, 28, 78],
        [76, 34, 59, 87, 33],
        [76, 73, 47, 59, 12],
        [27, 36, 22, 62, 98],
        [89, 76, 29, 90, 70]],

       [[33, 90, 67, 84, 98],
        [19, 93, 40, 68, 32],
        [12, 86,  7, 99, 35],
        [33, 22,  8, 59,  2],
        [16, 21, 81, 41, 25]]])

In [30]:
arr.ndim

3

### what is negative 1 in reshape


In [31]:
arr = np.arange(1,111)

In [32]:
arr.size

110

In [33]:
arr.reshape(-1,5)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110]])

### seed function

In [37]:
## because of seed function it will not change randomly
np.random.seed(12)
arr = np.random.randint(1,101,10)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [38]:
arr.size

10

In [39]:
np.random.seed(12)
arr = np.random.randint(1,101,15).reshape(3,5)
arr

array([[76, 28,  7,  3,  4],
       [68, 77, 49, 23, 50],
       [53,  6, 14, 90, 35]])

In [40]:
arr.size

15

In [41]:
arr = np.array([5,10,15,20,25])

In [42]:
arr

array([ 5, 10, 15, 20, 25])

In [43]:
# indexing
arr[2]

15

### 1 : Create 2-d array

In [44]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [45]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### 2 : indexing using double bracket notation

In [46]:
matrix[0][1]

10

In [47]:
matrix[1][1]

25

### 3 : indexing using single bracket notation (Recommented)

In [48]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [49]:
matrix[0,1]

10

In [50]:
matrix[2,2]

45

### 4 : Slicing  using single bracket notation

In [51]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
# [[5,10],
# [20,25]]

In [53]:
matrix[:2, :2]

array([[ 5, 10],
       [20, 25]])

In [54]:
matrix[1:, 1:] 

array([[25, 30],
       [40, 45]])

In [55]:
np.random.seed(123)
matrix2 = np.random.randint(1,101,25).reshape(5,5)
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [56]:
matrix2[1:4, 1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

In [57]:
matrix2[2:, 2:]

array([[47, 97, 26],
       [37, 97, 81],
       [56, 68,  3]])

### 5 : View Vs Copy

In [59]:
arr = np.array([5,10,15,20,25,30])

In [60]:
#sliced_array = arr[2:5]
sliced_array = arr[2:5].copy()

In [61]:
sliced_array

array([15, 20, 25])

In [62]:
sliced_array[:] = 0

In [63]:
sliced_array

array([0, 0, 0])

In [64]:
arr

array([ 5, 10, 15, 20, 25, 30])

### 6 : Conditional Selection

In [65]:
arr = np.arange(1,11)

In [66]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [69]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [70]:
mask = arr > 5

In [71]:
arr[mask]

array([ 6,  7,  8,  9, 10])

In [72]:
arr[arr<4]

array([1, 2, 3])

In [73]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [74]:
arr[arr==5]

array([5])

### 6 : Operation on array with scaler

In [75]:
#arr = np.array([1,2,3,4])
arr = np.array([1,2,3,4]).reshape(2,2)
arr

array([[1, 2],
       [3, 4]])

In [76]:
arr * 2

array([[2, 4],
       [6, 8]])

In [77]:
arr

array([[1, 2],
       [3, 4]])

In [78]:
arr + 5

array([[6, 7],
       [8, 9]])

In [79]:
arr ** 2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [80]:
arr ** 4

array([[  1,  16],
       [ 81, 256]], dtype=int32)

### 7 : numerical operations of arrays

In [81]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [82]:
arr1+arr2

array([ 6,  8, 10, 12])

In [83]:
arr1*arr2

array([ 5, 12, 21, 32])

In [84]:
arr1/arr2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [85]:
arr1**arr2

array([    1,    64,  2187, 65536], dtype=int32)

In [86]:
arr1*arr1

array([ 1,  4,  9, 16])

### 8 :some more numerical functions

In [87]:
arr = np.array([2,80,1,97,5])

In [88]:
np.min(arr)

1

In [89]:
np.max(arr)

97

In [90]:
# it will print the pos of min num 
np.argmin(arr)

2

In [91]:
# it will print the pos of max num 
np.argmax(arr)

3

In [92]:
np.sqrt(arr)

array([1.41421356, 8.94427191, 1.        , 9.8488578 , 2.23606798])

In [93]:
# oiler number 2.71828^i that means 
# [ 2, 80,  1, 97,  5] this elements

np.exp(arr)

array([7.38905610e+00, 5.54062238e+34, 2.71828183e+00, 1.33833472e+42,
       1.48413159e+02])

In [94]:
arr

array([ 2, 80,  1, 97,  5])

In [95]:
np.sin(arr)

array([ 0.90929743, -0.99388865,  0.84147098,  0.37960774, -0.95892427])

In [96]:
np.cos(arr)

array([-0.41614684, -0.11038724,  0.54030231, -0.92514754,  0.28366219])

In [98]:
## Between 1 to 15 it will provide 50 number
## Return evenly spaced numbers over a specified interval
np.linspace(1,15,50)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [99]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [103]:
np.array([1,2,3,0], dtype = 'bool')

array([ True,  True,  True, False])

In [104]:
arr2 = np.array([1,0,1,1], dtype = 'bool')

In [105]:
arr2

array([ True, False,  True,  True])

In [106]:
for i in arr2:
    print(i)

True
False
True
True


### 9 : Numpy axis

In [107]:
np.random.seed(123)
matrix = np.random.randint(1,11,9).reshape(3,3)

In [108]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [109]:
np.sum(matrix)

39

In [110]:
matrix.sum()

39

In [111]:
np.min(matrix)

1

In [112]:
np.max(matrix)

10

In [113]:
# rows = 1 columns = 0
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [114]:
np.min(matrix, axis=1)

array([3, 2, 1])

In [115]:
np.max(matrix, axis=1)

array([ 7, 10,  7])

In [116]:
# now columns wise
np.min(matrix, axis =0)

array([2, 2, 1])

In [117]:
np.sum(matrix, axis=1)

array([13, 16, 10])

In [118]:
# accumalative sum
np.cumsum(matrix)

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39], dtype=int32)

In [120]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [121]:
np.cumsum(matrix, axis=0)

array([[ 3,  3,  7],
       [ 5,  7, 17],
       [12,  9, 18]], dtype=int32)

In [122]:
np.cumsum(matrix, axis=1)

array([[ 3,  6, 13],
       [ 2,  6, 16],
       [ 7,  9, 10]], dtype=int32)

In [123]:
np.prod(matrix, axis=1)

array([63, 80, 14])

### 10: Shuffle and unique

In [124]:
np.random.seed(123)
arr = np.random.randint(1,15,15)

In [125]:
arr

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [130]:
np.random.shuffle(arr)

In [131]:
arr

array([ 3,  7, 10,  7,  4,  2, 11,  2,  2,  1, 14,  3, 12, 10, 13])

In [132]:
np.unique(arr)

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [134]:
np.unique(arr).size

10

In [135]:
np.unique(arr, return_index=True, return_counts=True)

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([ 9,  5,  0,  4,  1,  2,  6, 12, 14, 10], dtype=int64),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))

### 11 : Horaizontal and Vertical Stacking

In [136]:
np.random.seed(123)
matrix1 = np.random.randint(1,20,9).reshape(3,3)
matrix2 = np.random.randint(20,40,9).reshape(3,3)

In [137]:
matrix1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [138]:
matrix2

array([[35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [139]:
np.hstack((matrix1, matrix2))

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [140]:
np.vstack((matrix1, matrix2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [141]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [142]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [143]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
arr3 = np.arange(20,41)
arr3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

In [145]:
fives = np.ones(10)*5
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [146]:
# create 1-d array and thn convert it into 3-d array

arr4 = np.random.randint(1,50,24).reshape(3,4,2)
arr4

array([[[33, 17],
        [ 5,  4],
        [ 3, 21],
        [40,  3]],

       [[21, 48],
        [49,  8],
        [42, 36],
        [29, 39]],

       [[34, 22],
        [31, 28],
        [35, 34],
        [13, 41]]])

In [147]:
# 25 number between 0 to 1
arr5 = np.random.rand(5,5)
arr5

array([[0.76599595, 0.77700444, 0.02798196, 0.17390652, 0.15408224],
       [0.07708648, 0.8898657 , 0.7503787 , 0.69340324, 0.51176338],
       [0.46426806, 0.56843069, 0.30254945, 0.49730879, 0.68326291],
       [0.91669867, 0.10892895, 0.49549179, 0.23283593, 0.43686066],
       [0.75154299, 0.48089213, 0.79772841, 0.28270293, 0.43341824]])

In [148]:
np.random.seed(123)
arr6 = np.random.randint(1,50,20)
arr6[arr6 % 2 == 0] = -1
arr6

array([-1,  3, 29, 35, 39, -1, -1, 43, 23, -1, 33, -1, -1, 33, 47, 33, -1,
       -1, -1, 15])